res:
	g++ -std=c++14 Res.cpp includes/Res.h includes/File.h File.cpp Header.cpp array.cpp -o Res

head:
	g++ -std=c++11  Header.cpp -o header
Array:
	g++ -std=c++14 includes/array.h array.cpp -o array

clean:
	rm -rf Res header
